import React from 'react'

export default function Main() {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit fuga excepturi qui impedit amet deleniti repellat ut sunt doloribus laboriosam provident debitis optio, fugit sit incidunt ratione laudantium nam facere atque molestias rerum eos possimus harum. Corrupti et assumenda quibusdam libero delectus atque cumque consequuntur numquam nobis deserunt dicta fugiat laborum ex aperiam, corporis, natus, deleniti doloribus animi ut nemo alias tempore! Maiores odit doloremque quidem nulla, tempore quaerat rerum veniam facilis magni eveniet perferendis pariatur dolorem saepe adipisci error a consequuntur nesciunt et excepturi minima nobis culpa maxime. Ex eaque deleniti cupiditate, velit suscipit ullam eligendi, molestias reiciendis repellendus magnam provident maxime corrupti ab! Autem optio vitae soluta blanditiis suscipit sit corporis rerum non ea obcaecati fugit totam cumque laudantium accusamus pariatur vel error, esse eos. Porro veniam voluptatem odit deleniti non, unde quo, reiciendis possimus quaerat ratione tempora facere sunt saepe rerum earum fugiat perspiciatis eveniet molestiae deserunt quis dignissimos! Amet, id distinctio similique necessitatibus repudiandae a nostrum doloribus quae ab ratione consectetur sed fuga esse minus consequatur omnis adipisci eligendi sit. Nostrum exercitationem cum ex. Quia consectetur voluptatibus, voluptatem maxime saepe velit laboriosam explicabo eum maiores libero debitis laudantium natus molestias amet fugit quae quod pariatur odio aspernatur iure exercitationem eius cum perferendis. Ratione velit harum obcaecati, non vero aliquid quod debitis dolore sapiente in similique rem est vitae dolorum. Facilis rem iure ad dignissimos iusto sapiente repellendus totam voluptatum natus reiciendis dolor culpa labore amet repudiandae, quia, mollitia sequi eaque voluptatibus voluptates dolorem vero molestiae reprehenderit. Maxime cumque magni quam accusantium minima architecto aliquid blanditiis exercitationem quasi numquam facere nisi sit nobis dolor deserunt, praesentium corrupti, quae consequuntur error voluptas sunt! Pariatur inventore quasi sint, est, saepe autem possimus magni et praesentium doloremque enim expedita perspiciatis vero totam temporibus. Deleniti, quidem at odit inventore quisquam sint.</p>
    </div>
  )
}
